// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXX5JPmpMKlVuoeraAwm_uoKNmpQEwyLQ',
    appId: '1:283570847040:web:3f44094c8074e786dd0ea5',
    messagingSenderId: '283570847040',
    projectId: 'fasum-f18d0',
    authDomain: 'fasum-f18d0.firebaseapp.com',
    storageBucket: 'fasum-f18d0.firebasestorage.app',
    measurementId: 'G-CYMCV0WP23',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdedx6WuNofEkFfmLkIf4Uyv8I_zSvgNA',
    appId: '1:283570847040:android:6c58cd80e4636e38dd0ea5',
    messagingSenderId: '283570847040',
    projectId: 'fasum-f18d0',
    storageBucket: 'fasum-f18d0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFDeTGWm3fPo9Xeu-2mi1TJigOsKD6a_4',
    appId: '1:283570847040:ios:3e4a40899ccb1ca8dd0ea5',
    messagingSenderId: '283570847040',
    projectId: 'fasum-f18d0',
    storageBucket: 'fasum-f18d0.firebasestorage.app',
    iosBundleId: 'com.example.fasum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFDeTGWm3fPo9Xeu-2mi1TJigOsKD6a_4',
    appId: '1:283570847040:ios:3e4a40899ccb1ca8dd0ea5',
    messagingSenderId: '283570847040',
    projectId: 'fasum-f18d0',
    storageBucket: 'fasum-f18d0.firebasestorage.app',
    iosBundleId: 'com.example.fasum',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXX5JPmpMKlVuoeraAwm_uoKNmpQEwyLQ',
    appId: '1:283570847040:web:bb88a100e98cc484dd0ea5',
    messagingSenderId: '283570847040',
    projectId: 'fasum-f18d0',
    authDomain: 'fasum-f18d0.firebaseapp.com',
    storageBucket: 'fasum-f18d0.firebasestorage.app',
    measurementId: 'G-TGGRBF5GLP',
  );
}
